theme: jekyll-theme-cayman
show_downloads: false
latest_release_url: https://github.com/amirhp-com/Notion-RTL-macOS/releases/latest/download/NotionRTL-v2.zip
github:
  zip_url: https://github.com/amirhp-com/Notion-RTL-macOS/releases/latest/download/NotionRTL-v2.zip
